format = '$time$all$character'

[line_break]
disabled = true

[directory]
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 100
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
deleted = '󰅖'

[status]
disabled = false
symbol = ' '

[time]
disabled = false
time_format = "%T"
format = '[󰅐 $time]($style) '
